spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

  mvc:
    async:
       request-timeout: 20000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root


server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  INFO
    org.mybatis:  INFO
    org.zkz.litemall.wx:  DEBUG
    org.zkz.litemall:  DEBUG

swagger:
  production: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/