package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.MoneyLog;
import org.linlinjava.litemall.db.domain.MoneyLogExample;

public interface MoneyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    long countByExample(MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int deleteByExample(MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int insert(MoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int insertSelective(MoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    MoneyLog selectOneByExample(MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    MoneyLog selectOneByExampleSelective(@Param("example") MoneyLogExample example, @Param("selective") MoneyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    List<MoneyLog> selectByExampleSelective(@Param("example") MoneyLogExample example, @Param("selective") MoneyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    List<MoneyLog> selectByExample(MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    MoneyLog selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") MoneyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    MoneyLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MoneyLog record, @Param("example") MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MoneyLog record, @Param("example") MoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MoneyLog record);
}