package org.zkz.litemall.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.zkz.litemall.db.domain.MoneyPackage;
import org.zkz.litemall.db.domain.MoneyPackageExample;

public interface MoneyPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    long countByExample(MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int deleteByExample(MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int insert(MoneyPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int insertSelective(MoneyPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    MoneyPackage selectOneByExample(MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    MoneyPackage selectOneByExampleSelective(@Param("example") MoneyPackageExample example, @Param("selective") MoneyPackage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    List<MoneyPackage> selectByExampleSelective(@Param("example") MoneyPackageExample example, @Param("selective") MoneyPackage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    List<MoneyPackage> selectByExample(MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    MoneyPackage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MoneyPackage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    MoneyPackage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MoneyPackage record, @Param("example") MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MoneyPackage record, @Param("example") MoneyPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MoneyPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MoneyPackage record);
}