spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  INFO
    org.mybatis:  INFO
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  DEBUG

swagger:
  production: false