db:
  server: localhost
  port: 3306
  username: root
  password: 123456
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#spring:
#  redis:
#    host: www.test.com
#    password: ${common.password}
