package org.zkz.litemall.core.entity;

import org.zkz.litemall.db.domain.LitemallGoods;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class EsItem implements Serializable {

    private static final long serialVersionUID = -4001786119212330546L;



    private String name;

    private String brief;
    private Long id;



    private String goodsSn;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.gallery
     *
     * @mbg.generated
     */
    private String[] gallery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.keywords
     *
     * @mbg.generated
     */
    private String keywords;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.is_on_sale
     *
     * @mbg.generated
     */
    private Boolean isOnSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.sort_order
     *
     * @mbg.generated
     */
    private Short sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.share_url
     *
     * @mbg.generated
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.is_new
     *
     * @mbg.generated
     */
    private Boolean isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.is_hot
     *
     * @mbg.generated
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.counter_price
     *
     * @mbg.generated
     */
    private BigDecimal counterPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.retail_price
     *
     * @mbg.generated
     */
    private BigDecimal retailPrice;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_goods.detail
     *
     * @mbg.generated
     */
    private String detail;

    public static List<EsItem> tranferToEsItem(List<LitemallGoods> goodsList) {
        List<EsItem> result = new ArrayList<>();
        if (goodsList != null && !goodsList.isEmpty()) {

            goodsList.forEach(goods -> {
                EsItem item = new EsItem();
//                item.setBrandId(goods.getBrandId().longValue());
                item.setBrief(goods.getBrief());
//                item.setCategoryId(goods.getCategoryId().longValue());
                item.setCounterPrice(goods.getCounterPrice());
                item.setDeleted(goods.getDeleted());
                item.setDetail(goods.getDetail());
                item.setGallery(goods.getGallery());
                item.setGoodsSn(goods.getGoodsSn());
                item.setHot(goods.getIsHot());
                item.setId(goods.getId().longValue());
                item.setKeywords(goods.getKeywords());
                item.setName(goods.getName());
                item.setShareUrl(goods.getShareUrl());
                item.setUnit(goods.getUnit());
                item.setPicUrl(goods.getPicUrl());
                item.setSortOrder(goods.getSortOrder());
                item.setRetailPrice(goods.getRetailPrice());
                item.setOnSale(goods.getIsOnSale());
                item.setNew(goods.getIsNew());
                result.add(item);
            });


        }
        return result;
    }

    @Override
    public String toString() {
        return "EsItem{" +
                "name='" + name + '\'' +
                ", brief='" + brief + '\'' +
                ", id=" + id +
                ", goodsSn='" + goodsSn + '\'' +
                ", categoryId=" + categoryId +
                ", brandId=" + brandId +
                ", gallery=" + Arrays.toString(gallery) +
                ", keywords='" + keywords + '\'' +
                ", isOnSale=" + isOnSale +
                ", sortOrder=" + sortOrder +
                ", picUrl='" + picUrl + '\'' +
                ", shareUrl='" + shareUrl + '\'' +
                ", isNew=" + isNew +
                ", isHot=" + isHot +
                ", unit='" + unit + '\'' +
                ", counterPrice=" + counterPrice +
                ", retailPrice=" + retailPrice +
                ", deleted=" + deleted +
                ", detail='" + detail + '\'' +
                '}';
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrief() {
        return brief;
    }

    public void setBrief(String brief) {
        this.brief = brief;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGoodsSn() {
        return goodsSn;
    }

    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getBrandId() {
        return brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    public String[] getGallery() {
        return gallery;
    }

    public void setGallery(String[] gallery) {
        this.gallery = gallery;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public Boolean getOnSale() {
        return isOnSale;
    }

    public void setOnSale(Boolean onSale) {
        isOnSale = onSale;
    }

    public Short getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getShareUrl() {
        return shareUrl;
    }

    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    public Boolean getNew() {
        return isNew;
    }

    public void setNew(Boolean aNew) {
        isNew = aNew;
    }

    public Boolean getHot() {
        return isHot;
    }

    public void setHot(Boolean hot) {
        isHot = hot;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public BigDecimal getCounterPrice() {
        return counterPrice;
    }

    public void setCounterPrice(BigDecimal counterPrice) {
        this.counterPrice = counterPrice;
    }

    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }
}
